name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
# disabled windows due node packages issues
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        python-version: [ '2.x', '3.x', '3.5', '3.6', '3.7', '3.8', '3.9', 'pypy-2.7', 'pypy-3.6']
        exclude:
          - os: windows-latest
            python-version: '3.5'
          - os: macos-latest
            python-version: 'pypy-3.6'
    name: ${{ matrix.os }} ${{ matrix.arch }}, Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Python version
        run: python --version
      - name: Install packages
        run: pip install -r requirements.txt && pip install numpy
      - name: Simple tests
        run: python simple_test.py
